### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "umer@umer.com",
  "password": "umerumer"
}

### Find a particular user with ID
GET http://localhost:3000/auth/1

### Find all users
GET http://localhost:3000/auth?email=umer@umer.com

### Delete a user
DELETE http://localhost:3000/auth/5

### Update a user
PATCH http://localhost:3000/auth/1
Content-Type: application/json

{
  "email": "umer@umer.com",
  "password": "umerumer"
}